FROM balenalib/%%BALENA_MACHINE_NAME%%-ubuntu-python:3.7-bionic-build

WORKDIR /usr/src/app

RUN pip3 install wheel rpi-gpio adafruit-blinka adafruit-circuitpython-ht16k33 requests

COPY *.py ./

CMD ["python3", "counter.py"]
